---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-application-deployment
spec:
  selector:
    matchLabels:
      app: nginx-application
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-application
    spec:
      serviceAccountName: application
      containers:
      - name: nginx  
        image: nginx:1.14.2
        ports:
        - containerPort: 80
